"""Courses updated

Revision ID: e022ee2497c0
Revises: e8693d4a748f
Create Date: 2024-09-10 16:00:09.906155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e022ee2497c0'
down_revision = 'e8693d4a748f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('student',
    sa.Column('std_id', sa.Integer(), nullable=False),
    sa.Column('std_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('std_id')
    )
    op.create_table('enrollment',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('std_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['std_id'], ['student.std_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    op.drop_table('student')
    op.drop_table('course')
    # ### end Alembic commands ###
